=== MAIF/yozefu/docs/json-schemas/exported-kafka-record.json
{
  "$id": "https://raw.githubusercontent.com/MAIF/yozefu/refs/heads/main/docs/json-schemas/exported-kafka-record.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "ExportedKafkaRecord",
  "description": "An exported Kafka record is a wrapper around the `KafkaRecord` struct\nwith additional fields for analytics purposes.",
  "type": "object",
  "properties": {
    "topic": {
      "type": "string"
    },
    "timestamp": {
      "type": [
        "integer",
        "null"
      ],
      "format": "int64"
    },
    "partition": {
      "type": "integer",
      "format": "int32"
    },
    "offset": {
      "type": "integer",
      "format": "int64"
    },
    "headers": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    },
    "key_schema": {
      "anyOf": [
        {
          "$ref": "#/$defs/Schema"
        },
        {
          "type": "null"
        }
      ]
    },
    "value_schema": {
      "anyOf": [
        {
          "$ref": "#/$defs/Schema"
        },
        {
          "type": "null"
        }
      ]
    },
    "size": {
      "description": "Number of bytes for the key + the value",
      "type": "integer",
      "format": "uint",
      "minimum": 0,
      "default": 0
    },
    "key": {
      "description": "A human readable representation of the key",
      "$ref": "#/$defs/DataType"
    },
    "key_as_string": {
      "type": "string",
      "writeOnly": true
    },
    "value": {
      "description": "A human readable representation of the value",
      "$ref": "#/$defs/DataType"
    },
    "value_as_string": {
      "description": "The value as a string. needed to be displayed in the TUI",
      "type": "string",
      "writeOnly": true
    },
    "date_time": {
      "type": [
        "string",
        "null"
      ],
      "format": "date-time"
    },
    "absolute_delta_in_ms": {
      "description": "Milliseconds elapsed since the first exported kafka record.",
      "type": "integer",
      "format": "int64"
    },
    "relative_delta_in_ms": {
      "description": "Milliseconds elapsed since the previous exported kafka record.",
      "type": "integer",
      "format": "int64"
    },
    "search_query": {
      "type": "string"
    }
  },
  "required": [
    "topic",
    "partition",
    "offset",
    "headers",
    "key",
    "value",
    "absolute_delta_in_ms",
    "relative_delta_in_ms",
    "search_query"
  ],
  "$defs": {
    "Schema": {
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/$defs/SchemaId"
        },
        "schema_type": {
          "anyOf": [
            {
              "$ref": "#/$defs/SchemaType"
            },
            {
              "type": "null"
            }
          ]
        }
      },
      "required": [
        "id"
      ]
    },
    "SchemaId": {
      "type": "integer",
      "format": "uint32",
      "minimum": 0
    },
    "SchemaType": {
      "type": "string",
      "enum": [
        "JSON",
        "AVRO",
        "PROTOBUF"
      ]
    },
    "DataType": {
      "anyOf": [
        true,
        {
          "type": "string"
        }
      ]
    }
  }
}

=== MAIF/yozefu/crates/lib/tests/inputs/parsed-records/record-1.json
{
   "value": {
     "type": "Feature",
     "geometry": {
       "type": "Point",
       "coordinates": [
         4.0215,
         49.211613
       ]
     },
     "properties": {
       "label": "Rue Franz Kafka 51100 Reims",
       "score": 0.6992354545454544,
       "id": "51454_3782",
       "name": "Rue Franz Kafka",
       "postcode": "51100",
       "citycode": "51454",
       "x": 774438.44,
       "y": 6901804.03,
       "city": "Reims",
       "context": "51, Marne, Grand Est",
       "type": "street",
       "importance": 0.69159,
       "street": "Rue Franz Kafka"
     }
   },
   "key": "381",
   "topic": "public-french-addresses",
   "timestamp": 1732481153241,
   "partition": 0,
   "offset": 4,
   "headers": {},
   "key_schema": {
     "id": 1
   },
   "value_schema": {
     "id": 2
   },
   "size": 381,
   "date_time": "2024-11-24T21:45:53.241+01:00",
   "absolute_delta_in_ms": 0,
   "relative_delta_in_ms": 0,
   "search_query": ""
 }
